# Generated by Django 2.0.2 on 2018-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, max_length=25)),
                ('title_en', models.CharField(max_length=75)),
                ('description_en', models.CharField(blank=True, max_length=500)),
                ('publisher_en', models.CharField(blank=True, max_length=75)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
                ('eligible_for_release', models.CharField(blank=True, max_length=5)),
                ('program_alignment_architecture_en', models.CharField(blank=True, max_length=75)),
                ('portal_url_en', models.CharField(max_length=200)),
                ('user_votes', models.IntegerField(default=0)),
                ('owner_org', models.CharField(blank=True, max_length=75)),
                ('owner_org_title', models.CharField(blank=True, max_length=75)),
            ],
        ),
    ]
