# Generated by Django 2.0.2 on 2018-02-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_explorer', '0003_auto_20180226_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='title_en',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
