# Generated by Django 2.0.2 on 2018-02-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_explorer', '0004_auto_20180226_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description_en',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='publisher_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
