# Generated by Django 2.0.2 on 2018-02-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_explorer', '0005_auto_20180226_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='portal_url_en',
            field=models.CharField(blank=True, default='NaN', max_length=200),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='publisher_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
