# Generated by Django 2.0.2 on 2018-02-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_explorer', '0006_auto_20180226_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='size',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
