# Generated by Django 2.0.2 on 2018-02-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_explorer', '0007_auto_20180226_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='eligible_for_release',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owner_org',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owner_org_title',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='portal_url_en',
            field=models.CharField(default='NaN', max_length=200),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='program_alignment_architecture_en',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='title_en',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
